// Code generated by protoc-gen-go.
// source: bmi.proto
// DO NOT EDIT!

/*
Package bmi is a generated protocol buffer package.

It is generated from these files:
	bmi.proto

It has these top-level messages:
	BmiRequest
	BmiResponse
*/
package bmi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BmiRequest struct {
	Name   string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Height float32 `protobuf:"fixed32,2,opt,name=height" json:"height,omitempty"`
	Weight float32 `protobuf:"fixed32,3,opt,name=weight" json:"weight,omitempty"`
}

func (m *BmiRequest) Reset()                    { *m = BmiRequest{} }
func (m *BmiRequest) String() string            { return proto.CompactTextString(m) }
func (*BmiRequest) ProtoMessage()               {}
func (*BmiRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type BmiResponse struct {
	Bmi float32 `protobuf:"fixed32,1,opt,name=bmi" json:"bmi,omitempty"`
}

func (m *BmiResponse) Reset()                    { *m = BmiResponse{} }
func (m *BmiResponse) String() string            { return proto.CompactTextString(m) }
func (*BmiResponse) ProtoMessage()               {}
func (*BmiResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*BmiRequest)(nil), "BmiRequest")
	proto.RegisterType((*BmiResponse)(nil), "BmiResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for BmiCalculator service

type BmiCalculatorClient interface {
	Calculate(ctx context.Context, in *BmiRequest, opts ...client.CallOption) (*BmiResponse, error)
}

type bmiCalculatorClient struct {
	c           client.Client
	serviceName string
}

func NewBmiCalculatorClient(serviceName string, c client.Client) BmiCalculatorClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "bmicalculator"
	}
	return &bmiCalculatorClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *bmiCalculatorClient) Calculate(ctx context.Context, in *BmiRequest, opts ...client.CallOption) (*BmiResponse, error) {
	req := c.c.NewRequest(c.serviceName, "BmiCalculator.Calculate", in)
	out := new(BmiResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BmiCalculator service

type BmiCalculatorHandler interface {
	Calculate(context.Context, *BmiRequest, *BmiResponse) error
}

func RegisterBmiCalculatorHandler(s server.Server, hdlr BmiCalculatorHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&BmiCalculator{hdlr}, opts...))
}

type BmiCalculator struct {
	BmiCalculatorHandler
}

func (h *BmiCalculator) Calculate(ctx context.Context, in *BmiRequest, out *BmiResponse) error {
	return h.BmiCalculatorHandler.Calculate(ctx, in, out)
}

func init() { proto.RegisterFile("bmi.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0xca, 0xcd, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x0a, 0xe0, 0xe2, 0x72, 0xca, 0xcd, 0x0c, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x02, 0xb3, 0x85, 0xc4, 0xb8, 0xd8, 0x32, 0x52, 0x33, 0xd3, 0x33, 0x4a, 0x24, 0x98,
	0x14, 0x18, 0x35, 0x98, 0x82, 0xa0, 0x3c, 0x90, 0x78, 0x39, 0x44, 0x9c, 0x19, 0x22, 0x0e, 0xe1,
	0x29, 0xc9, 0x73, 0x71, 0x83, 0x4d, 0x2c, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x12, 0xe0, 0x62,
	0x4e, 0xca, 0xcd, 0x04, 0x9b, 0xc8, 0x14, 0x04, 0x62, 0x1a, 0x59, 0x72, 0xf1, 0x3a, 0xe5, 0x66,
	0x3a, 0x27, 0xe6, 0x24, 0x97, 0xe6, 0x24, 0x96, 0xe4, 0x17, 0x09, 0x69, 0x70, 0x71, 0xc2, 0x78,
	0xa9, 0x42, 0xdc, 0x7a, 0x08, 0xf7, 0x48, 0xf1, 0xe8, 0x21, 0x19, 0xa5, 0xc4, 0x90, 0xc4, 0x06,
	0x76, 0xb4, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xbb, 0x15, 0x31, 0xc1, 0x00, 0x00, 0x00,
}
